version: '3.8'

services:
  jenkins-server:
    image: jenkins/jenkins:lts-jdk17
    container_name: ${JENKINS_SERVER_NAME:-jenkins-server1}
    ports:
      - "8080:8080"
      - "50000:50000"  # Фиксированный порт для агента
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    restart: always

  jenkins-agent:
    build: .
    container_name: ${JENKINS_AGENT_NAME:-jenkins-agent1}
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/JenkinsLogs:/var/jenkins_agent
    environment:
      - JENKINS_URL=http://${JENKINS_SERVER_NAME}:8080  # Используем фиксированный порт
      - JENKINS_SECRET=d52a15f2332a89e37e0188a34ce23644269a237cc8f8bae9b9dca216af3f4da4
      - JENKINS_AGENT_NAME=GuestAgent
    restart: always

volumes:
  jenkins_home:
