version: '3.8'

services:
  jenkins-server:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

  jenkins-agent:
    image: jenkins/inbound-agent
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins-server:8080
      - JENKINS_SECRET=d52a15f2332a89e37e0188a34ce23644269a237cc8f8bae9b9dca216af3f4da4
      - JENKINS_AGENT_NAME=GuestAgent
    restart: always

volumes:
  jenkins_home: