version: '3.8'

services:
  app-container:
    image: my-app-image:${UNIQUE_ID}
    container_name: my-app-container-${UNIQUE_ID}
    ports:
      - "8080:8080" # Проброс порта для приложения
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
    external: true
