version: '3.8'

services:
  jenkins-server:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-server
    ports:
      - "8080:8000"
      - "50000:50000"
    environment:
      - JENKINS_OPTS=--httpPort=8000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_network
    restart: always

  jenkins-agent:
    build: .
    container_name: jenkins-agent
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/JenkinsLogs:/var/jenkins_agent
    environment:
      - JENKINS_URL=http://jenkins-server:8000
      - JENKINS_SECRET=d52a15f2332a89e37e0188a34ce23644269a237cc8f8bae9b9dca216af3f4da4
      - JENKINS_AGENT_NAME=GuestAgent
    depends_on:
      - jenkins-server
    networks:
      - jenkins_network
    restart: always

networks:
  jenkins_network:
    driver: bridge

volumes:
  jenkins_home:
